name: CI/CD Pipeline

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:
    branches:
      - "*"

jobs:
  dotnet:
    uses: HengineV5/.github/.github/workflows/dotnet-ci.yml@main
    with:
      nuget-packageid: "Henke.UtilLib"
      test-step: true